version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRESS_DB: nest
    networks:
      - nestjs-tutorial
  e2e-db:
    image: postgres:latest
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRESS_DB: nest
    networks:
      - nestjs-tutorial
networks:
  nestjs-tutorial:
