###

POST http://localhost:3333/auth/signup
Content-Type: application/json
Accept: application/json

{
    "email": "demo@gmail.com",
    "password": "password"
}

###
# @name loginAPI
POST http://localhost:3333/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "demo@gmail.com",
    "password": "password"
}

###

@token = {{loginAPI.response.body.$.access_token}}

###
GET http://localhost:3333/users/me
Authorization: Bearer {{token}}
